region                      = " eu-central-1"
sbcli_pkg                   = "sbcli-release"
mgmt_nodes                  = 1
storage_nodes               = 3
extra_nodes                 = 0
mgmt_nodes_instance_type    = "m5.large"
storage_nodes_instance_type = "i3en.large"
extra_nodes_instance_type   = "m6id.large"
volumes_per_storage_nodes   = 1
enable_apigateway           = 0
env                         = "prod"
