[tox]
envlist = tests, lint, types
skipsdist = true

[testenv]
basepython = python3.13

[testenv:lint]
deps = ruff
commands = ruff check

[testenv:types]
deps =
    -r requirements.txt
    -r type-requirements.txt
    mypy
commands = mypy simplyblock_web simplyblock_cli simplyblock_core

[testenv:tests]
deps = -r requirements.txt
commands = pytest {posargs}
