version: '3.8'

x-service-base: &service-base
  logging:
    driver: gelf
    options:
      gelf-address: "tcp://${CLUSTER_IP}:12202"


services:

  fdb-server:
    <<: *service-base
    image: foundationdb/foundationdb:7.3.63
    networks:
      - hostnet
    environment:
      SIMPLYBLOCK_LOG_LEVEL: '$LOG_LEVEL'
      FDB_CLUSTER_FILE_CONTENTS: '$FDB_CLUSTER_FILE_CONTENTS'
      FDB_NETWORKING_MODE: 'container'
      FDB_CLUSTER_FILE: '/etc/foundationdb/fdb.cluster'
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
      - "/etc/foundationdb/data:/var/fdb/data"
      - "/etc/foundationdb/logs:/var/fdb/logs"

    deploy:
      mode: global
      placement:
        constraints: [ node.role == manager ]
      resources:
        reservations:
          memory: 4g

  fdb-backup-agent:
    <<: *service-base
    image: foundationdb/foundationdb:7.3.63
    entrypoint: "/usr/bin/backup_agent -C  /etc/foundationdb/fdb.cluster"
    networks:
      - hostnet
    environment:
      FDB_CLUSTER_FILE: '/etc/foundationdb/fdb.cluster'
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
    deploy:
      placement:
        constraints: [ node.role == manager ]

  WebAppAPI:
    <<: *service-base
    image: $SIMPLYBLOCK_DOCKER_IMAGE
    command: "python3 simplyblock_web/app.py"
    networks:
      - localnet
    deploy:
      endpoint_mode: dnsrr
      mode: global
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"
      FLASK_DEBUG: "False"
      FLASK_ENV: "production"

  StorageNodeMonitor:
    <<: *service-base
    image: $SIMPLYBLOCK_DOCKER_IMAGE
    command: "python3 simplyblock_core/services/storage_node_monitor.py"
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
    networks:
      - hostnet
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"

  MgmtNodeMonitor:
    <<: *service-base
    image: $SIMPLYBLOCK_DOCKER_IMAGE
    command: "python3 simplyblock_core/services/mgmt_node_monitor.py"
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
    networks:
      - hostnet
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"

  LVolStatsCollector:
    <<: *service-base
    image: $SIMPLYBLOCK_DOCKER_IMAGE
    command: "python3 simplyblock_core/services/lvol_stat_collector.py"
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
    networks:
      - hostnet
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"

  MainDistrEventCollector:
    <<: *service-base
    image: $SIMPLYBLOCK_DOCKER_IMAGE
    command: "python3 simplyblock_core/services/main_distr_event_collector.py"
    networks:
      - hostnet
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"

  HAProxy:
    image: haproxytech/haproxy-debian:latest
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
    ports:
      - 80:80
      - 12202:12202
      - 9200:9200
      - 9090:9090
    networks:
      - localnet
      - monitoring-net
    volumes:
      - "$DIR/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"

  CapacityAndStatsCollector:
    <<: *service-base
    image: $SIMPLYBLOCK_DOCKER_IMAGE
    command: "python3 simplyblock_core/services/capacity_and_stats_collector.py"
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
    networks:
      - hostnet
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"

  CapacityMonitor:
    <<: *service-base
    image: $SIMPLYBLOCK_DOCKER_IMAGE
    command: "python3 simplyblock_core/services/cap_monitor.py"
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
    networks:
      - hostnet
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"

  HealthCheck:
    <<: *service-base
    image: $SIMPLYBLOCK_DOCKER_IMAGE
    command: "python3 simplyblock_core/services/health_check_service.py"
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
    networks:
      - hostnet
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"

  DeviceMonitor:
    <<: *service-base
    image: $SIMPLYBLOCK_DOCKER_IMAGE
    command: "python3 simplyblock_core/services/device_monitor.py"
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
    networks:
      - hostnet
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"

  LVolMonitor:
    <<: *service-base
    image: $SIMPLYBLOCK_DOCKER_IMAGE
    command: "python3 simplyblock_core/services/lvol_monitor.py"
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
    networks:
      - hostnet
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"

  SnapshotMonitor:
    <<: *service-base
    image: $SIMPLYBLOCK_DOCKER_IMAGE
    command: "python3 simplyblock_core/services/snapshot_monitor.py"
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
    networks:
      - hostnet
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"

  CleanupFDB:
    <<: *service-base
    image: $SIMPLYBLOCK_DOCKER_IMAGE
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"
      LOG_DELETION_INTERVAL: "${LOG_DELETION_INTERVAL}"
    command: "python3 simplyblock_core/workers/cleanup_foundationdb.py"
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
    networks:
      - hostnet

  TasksRunnerRestart:
    <<: *service-base
    image: $SIMPLYBLOCK_DOCKER_IMAGE
    command: "python3 simplyblock_core/services/tasks_runner_restart.py"
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
    networks:
      - hostnet
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"

  TasksRunnerMigration:
    <<: *service-base
    image: $SIMPLYBLOCK_DOCKER_IMAGE
    command: "python3 simplyblock_core/services/tasks_runner_migration.py"
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
    networks:
      - hostnet
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"

  TasksRunnerLVolMigration:
    <<: *service-base
    image: $SIMPLYBLOCK_DOCKER_IMAGE
    command: "python3 simplyblock_core/services/tasks_runner_lvol_migration.py"
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
    networks:
      - hostnet
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"

  TasksRunnerFailedMigration:
    <<: *service-base
    image: $SIMPLYBLOCK_DOCKER_IMAGE
    command: "python3 simplyblock_core/services/tasks_runner_failed_migration.py"
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
    networks:
      - hostnet
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"

  TasksRunnerClusterStatus:
    <<: *service-base
    image: $SIMPLYBLOCK_DOCKER_IMAGE
    command: "python3 simplyblock_core/services/tasks_cluster_status.py"
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
    networks:
      - hostnet
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"

  TasksRunnerNewDeviceMigration:
    <<: *service-base
    image: $SIMPLYBLOCK_DOCKER_IMAGE
    command: "python3 simplyblock_core/services/tasks_runner_new_dev_migration.py"
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
    networks:
      - hostnet
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"

  TasksNodeAddRunner:
    <<: *service-base
    image: $SIMPLYBLOCK_DOCKER_IMAGE
    command: "python3 simplyblock_core/services/tasks_runner_node_add.py"
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
    networks:
      - hostnet
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"

  TasksRunnerPortAllow:
    <<: *service-base
    image: $SIMPLYBLOCK_DOCKER_IMAGE
    command: "python3 simplyblock_core/services/tasks_runner_port_allow.py"
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
    networks:
      - hostnet
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"

  TasksRunnerJCCompResume:
    <<: *service-base
    image: $SIMPLYBLOCK_DOCKER_IMAGE
    command: "python3 simplyblock_core/services/tasks_runner_jc_comp.py"
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
    networks:
      - hostnet
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"

  TasksRunnerLVolSyncDelete:
    <<: *service-base
    image: $SIMPLYBLOCK_DOCKER_IMAGE
    command: "python3 simplyblock_core/services/tasks_runner_sync_lvol_del.py"
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
    networks:
      - hostnet
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"

  TasksRunnerBackup:
    <<: *service-base
    image: $SIMPLYBLOCK_DOCKER_IMAGE
    command: "python3 simplyblock_core/services/tasks_runner_backup.py"
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
    networks:
      - hostnet
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"

  TasksRunnerBackupMerge:
    <<: *service-base
    image: $SIMPLYBLOCK_DOCKER_IMAGE
    command: "python3 simplyblock_core/services/tasks_runner_backup_merge.py"
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
    networks:
      - hostnet
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"

  SnapshotReplication:
    <<: *service-base
    image: $SIMPLYBLOCK_DOCKER_IMAGE
    command: "python3 simplyblock_core/services/snapshot_replication.py"
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/etc/foundationdb:/etc/foundationdb"
    networks:
      - hostnet
    environment:
      SIMPLYBLOCK_LOG_LEVEL: "$LOG_LEVEL"

networks:
  monitoring-net:
    external: true

  hostnet:
    external: true
    name: host

  localnet:
    driver: overlay
    ipam:
      config:
        - subnet: 192.168.1.0/24
