# syntax=docker/dockerfile:1
FROM registry.access.redhat.com/ubi10/ubi:10.2

LABEL name="simplyblock"
LABEL vendor="Simplyblock"
LABEL version="1.0.0"
LABEL release="1"
LABEL summary="Simplyblock controlplane plane component"
LABEL description="Simplyblock controlplane plane container"
LABEL maintainer="developers@simplyblock.io"

RUN dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-10.noarch.rpm

RUN dnf install -y wget dmidecode pciutils sudo nano gdisk openssh-clients util-linux pkg-config hostname\
    ca-certificates curl kmod python3.13 python3-pip iputils iproute iscsi-initiator-utils \
    procps-ng libcap-2.69 openssh-9.9p1 systemd-257

ARG TARGETPLATFORM
RUN if [ "$TARGETPLATFORM" = "linux/arm64" ]; then \
        echo "ARM64 version"; \
    	wget https://github.com/apple/foundationdb/releases/download/7.3.69/foundationdb-clients-7.3.69-1.el9.aarch64.rpm; \
        rpm -ivh --nodigest --nofiledigest foundationdb-clients-7* ; \
        yum install https://www.rpmfind.net/linux/centos-stream/10-stream/BaseOS/aarch64/os/Packages/parted-3.6-7.el10.aarch64.rpm -y ; \
        yum install https://www.rpmfind.net/linux/centos-stream/10-stream/BaseOS/aarch64/os/Packages/libnvme-1.16.1-3.el10.aarch64.rpm -y ; \
        yum install https://www.rpmfind.net/linux/centos-stream/10-stream/BaseOS/aarch64/os/Packages/nvme-cli-2.16-2.el10.aarch64.rpm -y ; \
    else \
        echo "AMD64 version"; \
        wget https://github.com/apple/foundationdb/releases/download/7.3.69/foundationdb-clients-7.3.69-1.el7.x86_64.rpm; \
        rpm -ivh --nodigest --nofiledigest foundationdb-clients-7* ; \
        yum install https://www.rpmfind.net/linux/centos-stream/10-stream/BaseOS/x86_64/os/Packages/parted-3.6-7.el10.x86_64.rpm -y ; \
        yum install https://www.rpmfind.net/linux/centos-stream/10-stream/BaseOS/x86_64/os/Packages/libnvme-1.16.1-3.el10.x86_64.rpm -y ; \
        yum install https://www.rpmfind.net/linux/centos-stream/10-stream/BaseOS/x86_64/os/Packages/nvme-cli-2.16-2.el10.x86_64.rpm -y ; \
    fi

COPY LICENSE /licenses/LICENSE

WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip3 install --upgrade pip setuptools
RUN yum remove python-urllib3 -y
RUN pip3 install -r requirements.txt

RUN dnf upgrade -y

RUN dnf clean all

RUN useradd -ms /bin/bash simplyblock
RUN echo "simplyblock  ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
