name: Development Builder
on:
  push:
    branches:
      - 'main'

permissions:
  actions: write
  contents: write
  id-token: write

concurrency:
  group: "documentation"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - name: "Prepare Documentation Builder"
        run: |
          ./doc-builder build-image
      - name: "Build Documentation Test"
        run: |
          ./doc-builder update-repositories
          ./doc-builder build
  dev-deployment:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
        with:
          token: '${{ github.token }}'
      - name: "Prepare Documentation Builder"
        run: |
          ./doc-builder build-image
      - name: "Prepare Documentation Dev Deployment"
        run: |
          sed -i -r "s|(site_url: .*)|\1dev/|g" ./mkdocs.yml
          cat ./mkdocs.yml
          ./doc-builder update-repositories
          ./doc-builder build
      - name: "Creating Deployment Artifact"
        run: |
          mv site "${{ github.ref_name }}"
          ls -lah
          zip -r "${{ github.ref_name }}.zip" "${{ github.ref_name }}" -i "${{ github.ref_name }}/*"
      - name: "Uploading Dev Deployment"
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.ssh_server }}
          port: ${{ secrets.ssh_port }}
          username: ${{ secrets.ssh_username }}
          key: ${{ secrets.ssh_key }}
          source: "${{ github.ref_name }}.zip"
          target: .
      - name: "Deploying Dev Deployment"
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.ssh_server }}
          port: ${{ secrets.ssh_port }}
          username: ${{ secrets.ssh_username }}
          key: ${{ secrets.ssh_key }}
          script: |
            ./simplyblock_docs_dev_request_helper.sh ${{ github.ref_name }}